#!/usr/bin/bash

for conf_dir in $HOME/.config /etc; do
    if [[ -r ${conf_dir}/gitea-ssh.conf ]]; then
        source ${conf_dir}/gitea-ssh.conf
        break
    fi
done

/usr/bin/ssh -p ${GITEA_PORT:-2222} -o StrictHostKeyChecking=no ${GITEA_HOST:-git@localhost} \
    "SSH_ORIGINAL_COMMAND=\"${SSH_ORIGINAL_COMMAND}\" \
    /usr/local/bin/gitea $@"
